#!/bin/bash 
##########################################################
#
# Plugin To Check Free Disk Space
# Using Ssh_login
# Copyright (C) 2015 Eduardo Dimas (https://github.com/eddimas/nagios-plugins)
# 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##########################################################

j=0; ok=0
warn=0; crit=0
TEMP_FILE="/var/tmp/df.$RANDOM"

## Help funcion
help() {
  cat << END
Usage :
        check_disk.sh -i [STRING] -l [STRING] -H [STRING] -w [VALUE] -c [VALUE]
        OPTION          DESCRIPTION
        ----------------------------------
        -h              Help
	-i [STRING]     path to private key
        -l [STRING]     Remote user
        -H [STRING]     Host name
        -w [VALUE]      Warning Threshold
        -c [VALUE]      Critical Threshold
        -p [STRING]     Mountpoint
        ----------------------------------
Note : [VALUE] must be an integer.
END
}

if [ $# -eq 12 ]
then

	while getopts "i:l:H:w:c:p:" OPT
	do
	  case $OPT in
	    i) PRIVKEY="$OPTARG" ;;
	    l) USERNAME="$OPTARG" ;;
	    H) HOSTNAME="$OPTARG" ;;
	    w) WARN="$OPTARG" ;;
	    c) CRIT="$OPTARG" ;;
	    p) MOUNTPOINT="$OPTARG"
	       COMMAND="/bin/df -PH ${MOUNTPOINT}"
	    ;;
	    *) help 
	       exit 3		
            ;;
	  esac
	done
elif [ $# -eq 10 ]
then

        while getopts "i:l:H:w:c:" OPT
        do
          case $OPT in
            i) PRIVKEY="$OPTARG" ;;
            l) USERNAME="$OPTARG" ;;
            H) HOSTNAME="$OPTARG" ;;
            w) WARN="$OPTARG" ;;
            c) CRIT="$OPTARG" ;;
            *) help 
               exit 3
            ;;
          esac
        done
        COMMAND="/bin/df -PH"
fi

get_data () {
  ## Sending the ssh request command and store the result into local log file
  ssh -i ${PRIVKEY} -l ${USERNAME} ${HOSTNAME} -C ${COMMAND} > ${TEMP_FILE}.tmp
  cat ${TEMP_FILE}.tmp | grep -v Used | grep -v '0 0 0'|grep -ve '- - -' > ${TEMP_FILE}
  EQP_FS=$(cat ${TEMP_FILE} | grep -v Used |grep -v '0 0 0'|grep -ve '- - -' | wc -l)  # determine how many FS are in the server
}

process_data (){
  FILE=$TEMP_FILE                 # read $file using file descriptors
  exec 3<&0                       # save current stdin
  exec 0<"$FILE"                  # change it to read from file.

  while read LINE; do           # use $LINE variable to process each line of file
    j=$((j+1))
    FULL[$j]=`echo $LINE | awk '{print $2}'`
    USED[$j]=`echo $LINE | awk '{print $3}'`
    FREE[$j]=`echo $LINE | awk '{print $4}'`
    FSNAME[$j]=`echo $LINE | awk '{print $6}'`
    PERCENT[$j]=`echo $LINE | awk '{print $5}' | sed 's/[%]//g'`

  done
  exec 3<&0
  #rm $TEMP_FILE.tmp $TEMP_FILE
}

get_data
process_data

## According with the number of FS determine if the traceholds are reached (one by one)
for (( i=1; i<=$EQP_FS; i++ )); do
  if [ "${PERCENT[$i]}" -lt "${WARN}" ]; then
    ok=$((ok+1))
  elif [ "${PERCENT[$i]}" -eq "${WARN}" -o "${PERCENT[$i]}" -gt "${WARN}" -a "${PERCENT[$i]}" -lt "${CRIT}" ]; then
    warn=$((warn+1))
    WARN_DISKS[$warn]="${FSNAME[$i]} has ${PERCENT[$i]}% of utilization or ${USED[$i]} of ${FULL[$i]},"
  elif [ "${PERCENT[$i]}" -eq "${CRIT}" -o "${PERCENT[$i]}" -gt "${CRIT}" ]; then
    crit=$((crit+1))
    CRIT_DISKS[$crit]="${FSNAME[$i]} has ${PERCENT[$i]}% of utilization or ${USED[$i]} of ${FULL[$i]},"
  fi
done

## Set the data to show in the nagios service status
for (( i=1; i<=$EQP_FS; i++ )); do
  DATA[$i]="${FSNAME[$i]} ${PERCENT[$i]}% of ${FULL[$i]},"
  perf[$i]="${FSNAME[$i]}=${PERCENT[$i]}%;${WARN};${CRIT};0;;"
done

## Just validate and adjust the nagios output
if [ "$ok" -eq "$EQP_FS" -a "$warn" -eq 0 -a "$crit" -eq 0 ]; then
  echo "OK. DISK STATS: ${DATA[@]}"
  exit 0
elif [ "$warn" -gt 0 -a "$crit" -eq 0 ]; then
  echo "WARNING. DISK STATS: ${DATA[@]}_ Warning ${WARN_DISKS[@]}| ${perf[@]}"
  exit 1
elif [ "$crit" -gt 0 ]; then
  #Validate if the Warning array is empty if so remove the Warning leyend
  if [ ${#WARN_DISKS[@]} -eq 0 ]; then
    echo "CRITICAL. DISK STATS: ${DATA[@]}_ Critical ${CRIT_DISKS[@]}| ${perf[@]}"
    exit 2
  else
    echo "CRITICAL. DISK STATS: ${DATA[@]}_ Warning ${WARN_DISKS[@]}_ Critical ${CRIT_DISKS[@]}| ${perf[@]}"
    exit 2
  fi
else
  echo "Unknown"
  exit 3
fi
